### ISSUE TITLE
ffprobe "command not found" on recent build

### ISSUE THREAD

**Issue by Jimmdean-1** [ymgenesis/AudioTool#4]
AudioTool appears unable to gather stream information for my files, so cannot proceed.  Appears to be an issue with ffmpeg version as opposed to any problem with my file.  Built today - pulled from Plex Media Server for Mac 1.30.2.6563-3d4dc0cce (Jan 10, 2023).  Let me know what other information I can provide or what I might be doing wrong.

>>>>>>

Folder structure/file dependencies check satisfied!
Checking for correct input/output values...

input/output checks satisfied!

./audiotool.sh: line 656: ffprobe: command not found
./audiotool.sh: line 657: ffprobe: command not found
./audiotool.sh: line 658: ffprobe: command not found
./audiotool.sh: line 659: ffprobe: command not found
./audiotool.sh: line 660: ffprobe: command not found
./audiotool.sh: line 661: ffprobe: command not found
./audiotool.sh: line 662: ffprobe: command not found
./audiotool.sh: line 663: ffprobe: command not found
./audiotool.sh: line 664: ffprobe: command not found
./audiotool.sh: line 665: ffprobe: command not found
./audiotool.sh: line 666: ffprobe: command not found
./audiotool.sh: line 667: ffprobe: command not found
./audiotool.sh: line 668: ffprobe: command not found
./audiotool.sh: line 669: ffprobe: command not found
./audiotool.sh: line 670: ffprobe: command not found
./audiotool.sh: line 671: ffprobe: command not found
./audiotool.sh: line 672: ffprobe: command not found
./audiotool.sh: line 673: ffprobe: command not found
./audiotool.sh: line 674: ffprobe: command not found
./audiotool.sh: line 675: ffprobe: command not found
./audiotool.sh: line 676: ffprobe: command not found

>>>>>>>>

**Comment by Jimmdean-1** [comment]
my bad.  I guess I didn't understand I needed to download/install ffmpeg and ffprobe independently of your tool.  I guess I thought they were baked in to the Plex stuff that was copied over.

**Comment by Now2407** [comment]
Hey, I need help. The creator has not been on here for a while. Let me know. My thread is at the top.
